"use strict";

console.log("Script start:\n");

async function getRandomNumber(callerFn) {
  console.log(`\nFunction ${callerFn} started ...`);
  const randNum = Math.round(Math.random() * 100);
  console.log(`Random number generated by ${callerFn}: ${randNum}`);
  return randNum;
}

async function asyncWithoutAwait(callerFn) {
  console.log(`\nFunction ${callerFn} started ...`);
  const x = getRandomNumber(`getRandomNumber called in ${callerFn}`);
  console.log(x);
  console.log(`Function ${callerFn} ended.\n`);
}

async function asyncWithAwait(callerFn) {
  console.log(`\nFunction ${callerFn} started ...`);
  const x = await getRandomNumber(`getRandomNumber called in ${callerFn}`);
  console.log(x);
  console.log(`Function ${callerFn} ended.\n`);
}

async function asyncWithAwait2(callerFn) {
  console.log(`\nFunction ${callerFn} started ...`);
  const x = getRandomNumber(`getRandomNumber called in ${callerFn}`);
  console.log(await x);
  console.log(`Function ${callerFn} ended.\n`);
}

asyncWithAwait("asyncWithAwait");
asyncWithAwait2("asyncWithAwait2");
asyncWithoutAwait("asyncWithoutAwait");

console.log("\nScript end.\n");
